### ISSUE TITLE
RAW link nije u redu

### ISSUE THREAD

**Issue by deancupovic** [luka454/SI2014Tim12#1]
Linkovan je na facebook!

**Comment by luka454** [comment]
Poštovani asistente,

**Comment by luka454** [comment]
Poštovani asistente, 

link koji je unesen pogrešnim kopiranjem je ispravljen. Sada link na RAW radi ispravno. Nadam se da ovo nije problem jer je do greške došlo nenamjerno.

Sradačan pozdrav,
Luka

**Comment by deancupovic** [comment]
Svima -10 bodova :)
Naravno da nije problem. Zatvarajte issue kada završite.
